### ISSUE TITLE
Day 0: Space Traveler Hub Project

### ISSUE THREAD

**Issue by joyapisi** [joyapisi/space-traveler-hub#25]
## What we Have Done:
- [Project link](https://github.com/joyapisi/space-traveler-hub/projects/1)
- We have 2 people in our group ( @joyapisi  and @mnaibei )

**Comment by Owusu-Desmond** [comment]
Hi @joyapisi and @mnaibei , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/26gsvAm8UPaczzXz2/giphy.gif"/>

## Highlights
📌 Descriptive issue✅
📌 Great working on the setup of the project board ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
